title = "map1"
tile_size = 100
size = [100, 50]
spawn_places = [[1, 1, 3, 3], [97, 47, 99, 49]]

[[walls]]
x = 0
y = 0
width = 100
height = 1

[[walls]]
x = 0
y = 0
width = 1
height = 50

[[walls]]
x = 0
y = 49
width = 100
height = 1

[[walls]]
x = 99
y = 0
width = 1
height = 50
